version: "3.7"

services:
  api:
    build: .
    container_name: node_container
    restart: always
    volumes: 
      - .:/home/node/app
    ports: 
      - "${APP_PORT}:${APP_PORT}"
    command: npm start